lib: [
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/META"
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/dune-package"
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/ReasonRedisCrudLibrary.a" {"library/ReasonRedisCrudLibrary.a"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/ReasonRedisCrudLibrary.cma" {"library/ReasonRedisCrudLibrary.cma"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/ReasonRedisCrudLibrary.cmxa" {"library/ReasonRedisCrudLibrary.cmxa"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/Util.re" {"library/Util.re"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/Util.rei" {"library/Util.rei"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary.cmi" {"library/reasonRedisCrudLibrary.cmi"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary.cmt" {"library/reasonRedisCrudLibrary.cmt"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary.cmx" {"library/reasonRedisCrudLibrary.cmx"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary.ml" {"library/reasonRedisCrudLibrary.ml"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary__Util.cmi" {"library/reasonRedisCrudLibrary__Util.cmi"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary__Util.cmt" {"library/reasonRedisCrudLibrary__Util.cmt"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary__Util.cmti" {"library/reasonRedisCrudLibrary__Util.cmti"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/reasonRedisCrudLibrary__Util.cmx" {"library/reasonRedisCrudLibrary__Util.cmx"}
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/opam"
]
libexec: [
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/lib/reason-redis-crud/library/ReasonRedisCrudLibrary.cmxs" {"library/ReasonRedisCrudLibrary.cmxs"}
]
bin: [
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/bin/ReasonRedisCrudApp"
]
doc: [
  "/Users/mando/Github/reason-redis-crud/_esy/default/store/b/reason_redis_crud-c9bd27e2/install/default/doc/reason-redis-crud/README.md"
]
